tap "AdoptOpenJDK/openjdk"

cask "adoptopenjdk15"
cask "iterm2"
cask "google-chrome"
cask "alacritty"
cask "rectangle"
cask "slack"
cask "dbeaver-community"
cask "topnotch"
cask "1password"
cask "discord"
cask "android-studio"
cask "docker"
cask "istat-menus"
