tap "universal-ctags/universal-ctags"
tap "AdoptOpenJDK/openjdk"

brew "wget"
brew "neovim"
brew "ripgrep"
brew "fd"
brew "python"
brew "ctags", link: false
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
brew "the_silver_searcher"
brew "htop"
brew "bat"
brew "tmux"
brew "gpg"
brew "rust" 
brew "watchman" 
brew "zlib" 
brew "coreutils" 


cask "iterm2"
cask "google-chrome"
cask "alacritty"
cask "rectangle"
cask "slack"
cask "dbeaver-community"
cask "topnotch"
cask "1password"
cask "discord"
cask "android-studio"
cask "docker"
cask "istat-menus"
