Plug 'pangloss/vim-javascript'
Plug 'chase/vim-ansible-yaml'
Plug 'othree/javascript-libraries-syntax.vim'
Plug 'itspriddle/vim-jquery'
Plug 'jtratner/vim-flavored-markdown'
Plug 'kchmck/vim-coffee-script'
Plug 'scrooloose/syntastic'
Plug 'nelstrom/vim-markdown-preview'
Plug 'skwp/vim-html-escape'
Plug 'tpope/vim-haml'
Plug 'heartsentwined/vim-emblem'

" Plug 'garbas/vim-snipmate'
" Plug 'honza/vim-snippets'
