Plug 'ecomba/vim-ruby-refactoring'
Plug 'tpope/vim-rails'
Plug 'tpope/vim-rake'
Plug 'tpope/vim-rvm'
Plug 'tpope/vim-cucumber'
Plug 'vim-ruby/vim-ruby'
" Plug 'Keithbsmiley/rspec.vim'
Plug 'tpope/vim-bundler'
