NeoBundle 'pangloss/vim-javascript'
NeoBundle 'chase/vim-ansible-yaml'
NeoBundle 'othree/javascript-libraries-syntax.vim'
NeoBundle 'itspriddle/vim-jquery.git'
NeoBundle 'jtratner/vim-flavored-markdown.git'
NeoBundle 'kchmck/vim-coffee-script'
NeoBundle 'scrooloose/syntastic.git'
NeoBundle 'nelstrom/vim-markdown-preview'
NeoBundle 'skwp/vim-html-escape'
NeoBundle 'tpope/vim-haml'
NeoBundle 'heartsentwined/vim-emblem'

" NeoBundle 'garbas/vim-snipmate.git'
" NeoBundle 'honza/vim-snippets'
